Ahorcado.MVC/Models/Ahorcado.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;

namespace Ahorcado.MVC.Models
{
    public class Ahorcado
    {
        [DisplayName("Letra")]
        public String LetterTyped { get; set; }
        [DisplayName("Palabra")]
        public String WordToGuess { get; set; }
        [DisplayName("Letras acertadas")]
        public String GuessingWord { get; set; }
        [DisplayName("Chances Restantes")]
        public Int32? ChancesLeft { get; set; }
        [DisplayName("Letras Erradas")]
        public String WrongLetters { get; set; }

        public Boolean Win { get; set; }
    }
}

Ahorcado.MVC/Controllers/AhorcadoController.cs
using Ahorcado.Logica;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Ahorcado.MVC.Models;

namespace Ahorcado.MVC.Controllers
{
    public class AhorcadoController : Controller
    {


        public ActionResult AhorcadoView()
        {
            AhorcadoClass juego = new AhorcadoClass();
            juego.iniciarJuego();
            ViewBag.letrasIngresadas = "";
            return View(juego);
        }


        [HttpGet]
        public ActionResult siguienteRonda(int score)
        {
            AhorcadoClass juego = new AhorcadoClass();
            juego.iniciarJuego();
            juego.Juego.Score = score;
            ViewBag.letrasIngresadas = "";
            return View("AhorcadoView", juego);
        }

        [HttpPost]
        public ActionResult ArriesgarPalabra(string palAAdiv, int vidas, int scoreTot, string palabra, List<string> letIngresadas, string palModAct)
        {
            AhorcadoClass model;

            if (letIngresadas != null)
            {
                 model = new AhorcadoClass(palAAdiv, vidas, scoreTot, letIngresadas, palModAct);
            }
            else
            {
                 model = new AhorcadoClass(palAAdiv, vidas, scoreTot, palModAct);
            }

            string letras = "";

            model.IngresarPalabra(palabra);
            if (letIngresadas != null)
            {
                letras = string.Join(",", model.Juego.LetrasIngresadas.ToArray());
            }

            if (model.Juego.PalabraAAdivinar != palAAdiv)
            {
                model.Juego.PalabraAAdivinar = palAAdiv;
                return View("VictoriaView", model);
            }
            if(model.Juego.estaVivo == false)
            {
                return View("DerrotaView", model);
            } else
            {
                ViewBag.letrasIngresadas = letras;
                return View("AhorcadoView", model);
            }
        }

        [HttpPost]
        public ActionResult ArriesgarLetra(string palAAdiv, int vidas, int scoreTot, string letra, List<string> letIngresadas, string palModAct)
        {
            string letras = "";

            if (letIngresadas == null)
            {
                letIngresadas = new List<string>();
            }
            AhorcadoClass model = new AhorcadoClass(palAAdiv, vidas, scoreTot, letIngresadas, palModAct);
            model.IngresarLetra(letra);
            if (letIngresadas != null)
            {
                letras = string.Join(",", model.Juego.LetrasIngresadas.ToArray());
            }
            if (palAAdiv == model.Juego.PalabraModeloActual)
            {
                model.Juego.PalabraAAdivinar = palAAdiv;
                return View("VictoriaView", model);
            }
            else
            {
                if (model.Juego.estaVivo == false)
                {
                    return View("DerrotaView", model);
                }
                else
                {
                    ViewBag.letrasIngresadas = letras;
                    return View("AhorcadoView", model);
                }
            }
        }

        //[HttpGet]
        //public ActionResult _Derrota()
        //{
        //    VidaMuerteViewModel vm = new VidaMuerteViewModel();
        //    vm.Palabra = logica.Juego.PalabraAAdivinar;
        //    vm.Mensaje = "Lo siento, te quedaste sin vidas, mejor suerte la proxima";
        //    if(logica.Juego.Score > 0)
        //        return View("Error404");
        //    return View();
        //}
    }
}

Ahorcado.MVC/Views/Ahorcado/AhorcadoView.cshtml
@model AhorcadoClass
@{
    Layout = null;
    var letraslista = ViewBag.letrasIngresadas;
}

<!DOCTYPE html>
<script src="~/Scripts/Ahorcado/RecursosAhorcado.js"></script>

<html lang="es-ar">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Ahorcado</title>
    <style>

        .center{
            position: absolute;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
            border: 5px solid #FFFF00;
            padding: 10px;
        }


        .hor-center {
            left: 50%;
            padding: 10px;
        }

        .textAhorcado{
            font-family: 'Palatino Linotype';
            font-weight: bold;
        }


        .botones-ahorcado {
            background-color: #008CBA;
            font-size: 16px;
            border-radius: 12px;
            transition-duration: 0.4s;
            border: 2px solid #808080;
        }

        .botones-ahorcado:hover {
            background-color: #4CAF50; /* Green */
            color: white;
        }

    </style>
</head>

<body>
    <input type="hidden" id="palAAdiv" value="@Model.Juego.PalabraAAdivinar" />
    <input type="hidden" id="vidas" value="@Model.Juego.Vidas" />
    <input type="hidden" id="scoreTot" value="@Model.Juego.Score" />
    <div class="container center">
        <table aria-label="Cuadro de ordenamiento" class="table-responsive table-bordered" style="background-color:lightgray" width="600" height="200">
            <thead>
                <tr>
                    <td>
                        <h2> <label class="textAhorcado">&nbsp;&nbsp; cambio juego</label></h2>
                    </td>
                    <td style="width: 300px; text-align:center;">
                        <div>
                            @for (int i = 0; i < Model.Juego.Vidas; i++)
                            {
                                <img name="corazon" src="~/Imagenes/corazon.png" width="40" height="55" />
                            }
                            &nbsp;
                        </div>
                    </td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="left">
                        @*<form action="/Ahorcado/ArriesgarPalabra" method="post">
                            <label>Arriesgar Palabra </label>
                            <input type="hidden" id="palAAdiv" value="@Model.Juego.PalabraAAdivinar" />
                            <input type="text" name="palabra" placeholder="palabra" />
                            <input type="submit" value="Arriesgar" />
                            <br />
                        </form>*@
                        @using (Html.BeginForm("ArriesgarPalabra", "Ahorcado", FormMethod.Post))
                        {
                            <label class="textAhorcado">Arriesgar Palabra </label>
                            <input type="hidden" id="palAAdivP" name="palAAdiv" value="@Model.Juego.PalabraAAdivinar" />
                            <input type="hidden" id="vidasP" name="vidas" value="@Model.Juego.Vidas" />
                            <input type="hidden" id="scoreTotP" name="scoreTot" value="@Model.Juego.Score" />
                            <input type="hidden" id="palModActP" name="palModAct" value="@Model.Juego.PalabraModeloActual" />
                            for (int i = 0; i < Model.Juego.LetrasIngresadas.Count; i++)
                            {
                                <input type="hidden" id="letIngresadasP" name="letIngresadas[@i]" value="@Model.Juego.LetrasIngresadas[i]" />
                            }
                            <input type="text" id="palIngresada" name="palabra" placeholder="palabra" style="width: 50px;" />
                            <input type="submit" id="btnIngPal" value="Arriesgar"  class="botones-ahorcado" />
                            <br />
                        }

                        <br />

                        @using (Html.BeginForm("ArriesgarLetra", "Ahorcado", FormMethod.Post))
                        {
                            <label class="textAhorcado">Arriesgar Letra </label>
                            <input type="hidden" id="palAAdivL" name="palAAdiv" value="@Model.Juego.PalabraAAdivinar" />
                            <input type="hidden" id="vidasL" name="vidas" value="@Model.Juego.Vidas" />
                            <input type="hidden" id="scoreTotL" name="scoreTot" value="@Model.Juego.Score" />
                            for (int i = 0; i < Model.Juego.LetrasIngresadas.Count; i++)
                            {
                                <input type="hidden" id="letIngresadasL" name="letIngresadas[@i]" value="@Model.Juego.LetrasIngresadas[i]" />
                            }
                            <input type="hidden" id="palModActL" name="palModAct" value="@Model.Juego.PalabraModeloActual" />
                            <span>&nbsp;&nbsp;&nbsp;</span>
                            <input type="text" id="letraIngresada" name="letra" placeholder="letra" maxlength="1" style="width: 50px;" />
                            <input type="submit"  id="btnIngLet" value="Arriesgar"  class="botones-ahorcado" />
                            <br />
                        }
                    </td>
                    <td class="right" style="width: 300px;">
                        <label class="textAhorcado"  style="font-size:5mm">Score:</label>  <label id="score" class="textAhorcado">&nbsp;@Model.Juego.Score</label> <br />
                        <br />
                        <label class="textAhorcado" id="labelPalabra" style="font-size:5mm">Palabra:</label> <label id="palModAct" class="textAhorcado">&nbsp;@Model.Juego.PalabraModeloActual</label> <br />
                        <br />
                        <label class="textAhorcado" style="font-size:5mm">Letras Ingresadas: </label> <label id="listaLetra"  class="textAhorcado">&nbsp;@letraslista</label> <br />
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="hor-center"  style="background-color:lightgray; text-align:center;">
            @using (Html.BeginForm("AhorcadoView", "Ahorcado", FormMethod.Get))
            {
                <input type="submit" id="otraPartida" value="Otra partida" class="botones-ahorcado" />
                <br />
            }
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>

Ahorcado.MVC/Views/Ahorcado/DerrotaView.cshtml
@model AhorcadoClass
@{
    Layout = null;
}

<!DOCTYPE html>
<script src="~/Scripts/Ahorcado/RecursosAhorcado.js"></script>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Ahorcado</title>

    <style>

        .center {
            position: absolute;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
            border: 5px solid #FFFF00;
            padding: 10px;
        }


        .textAhorcado {
            font-family: 'Palatino Linotype';
            font-weight: bold;
        }

        .botones-ahorcado {
            background-color: #008CBA;
            font-size: 16px;
            border-radius: 12px;
            transition-duration: 0.4s;
            border: 2px solid #808080;
        }

            .botones-ahorcado:hover {
                background-color: #4CAF50; /* Green */
                color: white;
            }

    </style>

</head>
<body>
    <input type="hidden" id="palAAdiv" value="@Model.Juego.PalabraAAdivinar" />
    <input type="hidden" id="vidas" value="@Model.Juego.Vidas" />
    <input type="hidden" id="scoreTot" value="@Model.Juego.Score" />
    <div class="container center">
        <table class="table-responsive table-bordered" style="background-color:lightgray">
            <thead>
                <tr>
                    <td>
                        <h2 class="textAhorcado" style="text-align:center;">Ahorcado</h2>
                    </td>
                </tr>
                <tr>
                    <td style="text-align:center;">
                        <img id="imagenMuerte" src="~/Imagenes/muerte.png" width="150" height="100" />
                    </td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td style="text-align:center;">
                        <br />
                        <label id="labelHasMuerto" class="textAhorcado" style="font-size: 6mm;">¡¡HAS MUERTO!! La palabra a adivinar era: @Model.Juego.PalabraAAdivinar</label>
                    </td>
                </tr>
                <tr>
                    <td style="text-align:center;">
                        <br />
                        <label id="labelScore" class="textAhorcado"  style="font-size:5mm">Score final: @Model.Juego.Score</label>
                    </td>
                </tr>
                <tr>
                    <td style="text-align:center;">
                        @using (Html.BeginForm("AhorcadoView", "Ahorcado", FormMethod.Get))
                        {
                            <br />
                            <input id="botonSigPartida" class="botones-ahorcado" type="submit" value="Otra partida" />
                            <br />
                        }
                    </td>
                </tr>

            </tbody>
        </table>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>

Ahorcado.MVC/Views/Ahorcado/Index.cshtml
@model Ahorcado.MVC.Models.Ahorcado
@{
    ViewBag.Title = "Index";
}

@section scripts
{
    <script src="~/Scripts/Ahorcado/HangmanVM.js"></script>
    <script type="text/javascript">
        var hangVM = new HangmanVM(@Html.Raw(Model));
        ko.applyBindings(hangVM);
    </script>
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div class="container">
        <div class="panel panel-default" style="margin-top:20px;">
            <div class="panel-heading">
                <div class="panel-title">Ahorcado</div>
            </div>
            <div class="panel-body form-horizontal">
                <div class="col-sm-6">
                    <div class="form-group">
                        <div class="col-sm-3">
                            @Html.LabelFor(m => m.WordToGuess)
                        </div>
                        <div class="col-sm-3">
                            @Html.TextBoxFor(m => m.WordToGuess, new Dictionary<String, object>
                            {
                                { "class", "form-control" },
                                { "data-bind", "value:WordToGuess, enable:enableWordToGuess" },
                                { "type", "password" }
                            })
                        </div>
                        <div class="col-sm-6">
                            <button id="btnInsertWord" class="btn" data-bind="click: insertWordToGuess, enable:enableWordToGuess">Ingresar</button>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-3">
                            @Html.LabelFor(m => m.LetterTyped)
                        </div>
                        <div class="col-sm-3">
                            @Html.TextBoxFor(m => m.LetterTyped, new Dictionary<String, object>
                            {
                                { "class", "form-control" },
                                { "data-bind", "value:LetterTyped, enable: !enableWordToGuess()" },
                                { "maxlength", "1" }
                            })
                        </div>
                        <div class="col-sm-2">
                            <button id="btnInsertLetter" class="btn" data-bind="click: tryLetter, enable: !enableWordToGuess() && ChancesLeft() > 0 && !Win()">Probar</button>
                        </div>
                        <div class="col-sm-2">
                            <button id="btnResetGame" class="btn btn-primary" data-bind="click: resetGame, enable: (Win() || ChancesLeft() == 0) && !enableWordToGuess()">Resetear</button>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <div class="col-sm-6">
                            @Html.LabelFor(m => m.GuessingWord)
                        </div>
                        <div class="col-sm-6">
                            @Html.TextBoxFor(m => m.GuessingWord, new Dictionary<String, object>
                            {
                                { "class", "form-control" },
                                { "data-bind", "value:GuessingWord, enable: false" }
                            })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-6">
                            @Html.LabelFor(m => m.ChancesLeft)
                        </div>
                        <div class="col-sm-6">
                            @Html.TextBoxFor(m => m.ChancesLeft, new Dictionary<String, object>
                            {
                                { "class", "form-control" },
                                { "data-bind", "value:ChancesLeft, enable: false" }
                            })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-6">
                            @Html.LabelFor(m => m.WrongLetters)
                        </div>
                        <div class="col-sm-6">
                            @Html.TextBoxFor(m => m.WrongLetters, new Dictionary<String, object>
                            {
                                { "class", "form-control" },
                                { "data-bind", "value:WrongLetters, enable: false" }
                            })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <canvas id="hangmanCanvas" width="679" height="290"></canvas>
</body>
</html>

Ahorcado.MVC/Views/Ahorcado/VictoriaView.cshtml
@model AhorcadoClass
@{
    Layout = null;
}

<!DOCTYPE html>
<script src="~/Scripts/Ahorcado/RecursosAhorcado.js"></script>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Ahorcado</title>

    <style>

        .center {
            position: absolute;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
            border: 5px solid #FFFF00;
            padding: 10px;
        }


        .textAhorcado {
            font-family: 'Palatino Linotype';
            font-weight: bold;
        }

        .botones-ahorcado {
            background-color: #008CBA;
            font-size: 16px;
            border-radius: 12px;
            transition-duration: 0.4s;
            border: 2px solid #808080;
        }

            .botones-ahorcado:hover {
                background-color: #4CAF50; /* Green */
                color: white;
            }
    </style>

</head>
<body>
    <input type="hidden" id="palAAdiv" value="@Model.Juego.PalabraAAdivinar" />
    <input type="hidden" id="vidas" value="@Model.Juego.Vidas" />
    <input type="hidden" id="scoreTot" value="@Model.Juego.Score" />
    <div class="container center"> 

        <table class="table-responsive table-bordered" style="background-color:lightgray">
            <thead>
                <tr>
                    <td>
                        <h2 class="textAhorcado" style="text-align:center;">Ahorcado</h2>
                    </td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td style="text-align:center;">
                        <br />
                        <label id="labelVictoria" class="textAhorcado" style="font-size: 6mm;">¡¡CORRECTO!! La palabra a adivinar era: @Model.Juego.PalabraAAdivinar</label>
                    </td>
                </tr>
                <tr>
                    <td style="text-align:center;">
                        <br />
                        <label id="labelScore"  class="textAhorcado"  style="font-size:5mm">Score actual: @Model.Juego.Score</label>
                    </td>
                </tr>
                <tr>
                    <td style="text-align:center;">
                        @using (Html.BeginForm("siguienteRonda", "Ahorcado", FormMethod.Get))
                        {
                            <input type="hidden" id="score" name="score" value="@Model.Juego.Score" />
                            <br />
                            <input  id="botonContinuar" class="botones-ahorcado" type="submit" value="Jugar de Nuevo" />
                            <br />
                        }
                    </td>
                </tr>

            </tbody>
        </table>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>

Ahorcado.MVC/Views/Ahorcado/_Derrota.cshtml
@model  VidaMuerteViewModel

<h1>@Model.Mensaje</h1>
La palabra era @Model.Palabra


<button href="Ahorcado/Index" title="Iniciar otro juego"/>

Ahorcado.MVC/Views/Ahorcado/_Victoria.cshtml
@model  VidaMuerteViewModel

<h1>@Model.Mensaje</h1>
Acertaste la palabra @Model.Palabra con un Score de @Model.Score puntos.


<button href="Ahorcado/Index" title="Iniciar otro juego"/>